---

name: Build and Push Docker Image to Docker Hub

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
    tags-ignore: ['*']
  check_run:
    types: [rerequested, requested_action]
  pull_request:
    branches: ["master"]
# yamllint enable

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
             frankhjung/python:3.11.2
             frankhjung/python:latest
